//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testWord
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testWordEntities1 : DbContext
    {
        private static testWordEntities1 twe = null;

        public static testWordEntities1 GetTestWordEntities1()
        {
            if (twe == null)
                twe = new testWordEntities1();
            return twe;
        }

        public testWordEntities1()
            : base("name=testWordEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Бригады> Бригады { get; set; }
        public virtual DbSet<Задачи> Задачи { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
    }
}
