//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testWord
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public int КодСотрудника { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Фамилия { get; set; }
        public string Специальность { get; set; }
        public bool Должность { get; set; }
        public byte[] Фото { get; set; }
        public int Бригада { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
    
        public virtual Бригады Бригады { get; set; }
    }
}
